import Foundation
import LecternCore

/// A ~20-minute compilers lecture in a realistic speaking style (filler, restarts, admin, a student
/// question), covering LL(1) parsing → FIRST sets → FOLLOW sets → parse table construction → left
/// recursion elimination, plus the matching slide deck. "L" = lecturer, "S" = student.
enum ScriptedLecture {
    static let deck = SlideDeck(fileName: "ll1.pdf", originalFileName: "lecture07-ll1.pdf", title: "Lecture 7: Top-Down Parsing", pages: [
        SlidePage(number: 1, title: "Lecture 7: Top-Down Parsing", text: "CS 421 Compilers. Lecture 7: Top-Down Parsing. LL(1) parsing, FIRST and FOLLOW, parse tables."),
        SlidePage(number: 2, title: "Recap: recursive descent", text: "Recap: recursive descent. One procedure per nonterminal. Backtracking is expensive. Goal: predictive parsing without backtracking."),
        SlidePage(number: 3, title: "LL(1) parsing", text: "LL(1): scan input Left to right, produce a Leftmost derivation, using 1 token of lookahead. A predictive parser chooses the production A → α using the next input token. Driven by a parse table M[A, a] and a stack."),
        SlidePage(number: 4, title: "The LL(1) driver", text: "Stack holds grammar symbols, starts with S $. If top is terminal: match and advance. If top is nonterminal A: look up M[A, a], replace A with the production's right-hand side. Empty entry = syntax error."),
        SlidePage(number: 5, title: "FIRST sets", text: "FIRST(α) = set of terminals that begin strings derived from α. If α ⇒* ε then ε ∈ FIRST(α). FIRST(a) = {a} for a terminal a."),
        SlidePage(number: 6, title: "Computing FIRST", text: "For X → Y1 Y2 … Yk: add FIRST(Y1) − {ε}; if ε ∈ FIRST(Y1) add FIRST(Y2) − {ε}, and so on. If all Yi can derive ε, add ε. Iterate to a fixed point."),
        SlidePage(number: 7, title: "Example grammar", text: "E → T E'   E' → + T E' | ε   T → F T'   T' → * F T' | ε   F → ( E ) | id. FIRST(F) = FIRST(T) = FIRST(E) = { (, id }. FIRST(E') = { +, ε }. FIRST(T') = { *, ε }."),
        SlidePage(number: 8, title: "FOLLOW sets", text: "FOLLOW(A) = set of terminals that can appear immediately to the right of A in some sentential form. $ ∈ FOLLOW(S). For B → α A β: add FIRST(β) − {ε} to FOLLOW(A). If β ⇒* ε (or β empty): add FOLLOW(B) to FOLLOW(A)."),
        SlidePage(number: 9, title: "FOLLOW example", text: "FOLLOW(E) = FOLLOW(E') = { ), $ }. FOLLOW(T) = FOLLOW(T') = { +, ), $ }. FOLLOW(F) = { *, +, ), $ }."),
        SlidePage(number: 10, title: "Building the parse table", text: "For each production A → α: for each terminal a in FIRST(α), add A → α to M[A, a]. If ε ∈ FIRST(α): for each b in FOLLOW(A), add A → α to M[A, b]. A grammar is LL(1) iff no cell has more than one production."),
        SlidePage(number: 11, title: "Conflicts", text: "Two productions in one cell = conflict: the grammar is not LL(1). Causes: left recursion, common prefixes (need left factoring), ambiguity."),
        SlidePage(number: 12, title: "Left recursion", text: "A → A α | β is left recursive: a top-down parser loops forever. Rewrite: A → β A'   A' → α A' | ε. Same language, now right recursive. Indirect left recursion: A → B x, B → A y — order nonterminals and substitute."),
        SlidePage(number: 13, title: "Summary", text: "LL(1) = predictive, table-driven. Compute FIRST, then FOLLOW, then fill the table. Eliminate left recursion and left factor first. HW3 due Friday."),
    ])

    static let lines: [(String, String)] = [
        ("L", "Okay, can everyone hear me in the back? Yeah? Okay good. Let's get started."),
        ("L", "Um, so a couple of announcements first. Homework three is out, it's due next Friday at midnight, and it's basically all about what we're doing today, so pay attention."),
        ("L", "Also office hours this week are moved to Thursday because of the career fair. Okay."),
        ("L", "So last time we did recursive descent, right, one procedure per nonterminal, and I said the problem is backtracking. If you guess the wrong production you have to back up and that can be exponential."),
        ("L", "So today the goal is, can we parse top down without ever backtracking? And the answer is yes for a nice class of grammars, which we call LL one."),
        ("L", "So what does LL one mean. The first L is we scan the input left to right. The second L is we produce a leftmost derivation. And the one is we get to look at one token of lookahead. Just one."),
        ("L", "And the idea is, when I have a nonterminal A on top of my stack and I have to pick which production of A to use, I just peek at the next token and that uniquely tells me which production. No guessing."),
        ("L", "So how do we make that decision fast? We precompute a table. We call it the parse table, M of A comma a, rows are nonterminals, columns are terminals, and each cell tells you which production to use."),
        ("L", "And the driver is really simple. You've got a stack, it starts with the start symbol and the dollar sign, the end marker. If the top of the stack is a terminal, it has to match the input token, you pop it and advance. If it's a nonterminal, you look in the table and replace it with the right hand side."),
        ("L", "And if the cell is empty, that's a syntax error, you report it right there. So the whole parser is like twenty lines of code, all the intelligence is in the table."),
        ("L", "Let me just trace it really quick so you see it. Input is id plus id, then dollar. Stack is E dollar. Top is E, lookahead is id, the table says E goes to T E prime, so I pop E and push E prime then T. Now T with id, T goes to F T prime. F with id, F goes to id. Now the top is the terminal id and it matches, so I pop it and advance, lookahead is now plus."),
        ("L", "T prime with plus, hmm, T prime can't start with plus, so the table says use T prime goes to epsilon, just pop it. E prime with plus says E prime goes to plus T E prime. Match plus. And so on until the stack is just dollar and the input is dollar, and then we accept. Notice we never guessed, every step was one table lookup."),
        ("L", "Okay so the real question for the rest of the lecture is how do we build that table. And to build it we need two things, FIRST sets and FOLLOW sets. Let's start with FIRST."),
        ("L", "So FIRST of alpha, where alpha is any string of grammar symbols, is the set of terminals that can begin a string derived from alpha. So if alpha can eventually produce something that starts with plus, then plus is in FIRST of alpha."),
        ("L", "And there's one special case, if alpha can derive the empty string, epsilon, then we put epsilon in FIRST of alpha too. Just remember that, epsilon in FIRST means this thing can vanish."),
        ("L", "For a terminal it's trivial, FIRST of a is just a. For a nonterminal X with a production X goes to Y one Y two up to Y k, you add FIRST of Y one minus epsilon."),
        ("L", "And then, here's the key part, if Y one can derive epsilon, you also have to look at Y two, because Y one might vanish and then Y two is what actually starts the string. And if Y two can vanish you keep going to Y three and so on."),
        ("L", "And if every single Y i can derive epsilon, then X can derive epsilon, so you add epsilon to FIRST of X. And you just iterate this over all the productions until nothing changes. It's a fixed point computation."),
        ("L", "Let me do a tiny one before the big example. Say S goes to A B c, A goes to a or epsilon, B goes to b or epsilon. What's FIRST of S? Well A can start with a, so a is in. But A can vanish, so look at B, b is in. And B can vanish too, so we get to c, c is in. And c is a terminal, it can't vanish, so we stop. FIRST of S is a, b, c. No epsilon, because c is always there."),
        ("L", "People forget that last part all the time. You only add epsilon to FIRST of the left side if every symbol on the right can vanish. One terminal anywhere in there and epsilon is out."),
        ("S", "Wait, so is FIRST basically the same as the lookahead token?"),
        ("L", "Good question. Not quite. The lookahead is the actual next token in the input. FIRST is a property of the grammar, it's the set of tokens that could possibly show up. The parser checks whether the lookahead is in FIRST of a production to decide whether to use it."),
        ("L", "Okay let's do the example on the slide, the classic expression grammar. E goes to T E prime, E prime goes to plus T E prime or epsilon, T goes to F T prime, T prime goes to star F T prime or epsilon, and F goes to paren E paren or id."),
        ("L", "So FIRST of F is open paren and id, right, those are the only two ways F can start. T starts with F, so FIRST of T is the same, open paren and id. And E starts with T, so same again."),
        ("L", "FIRST of E prime is plus and epsilon, because E prime is either plus something or it vanishes. Same idea for T prime, star and epsilon. Everybody okay with that? Okay."),
        ("L", "Alright, so now the second ingredient. FOLLOW sets. And this is the one people usually get confused on, so let's go slowly."),
        ("L", "FOLLOW of A, for a nonterminal A, is the set of terminals that can appear immediately to the right of A in some sentential form. So not what A starts with, but what can come right after A."),
        ("L", "Why do we need this? Because of epsilon. If A can vanish, then to decide whether to use the epsilon production, I need to know, is the next token something that's allowed to come after A. That's exactly FOLLOW."),
        ("L", "The rules. First, the end marker dollar is always in FOLLOW of the start symbol. Then for every production B goes to alpha A beta, whatever beta can start with, FIRST of beta minus epsilon, goes into FOLLOW of A."),
        ("L", "And if beta can derive epsilon, or if A is at the very end of the production, then everything in FOLLOW of B goes into FOLLOW of A. Because if nothing comes after A inside this production, whatever follows B follows A."),
        ("L", "And again you iterate until a fixed point. Notice FOLLOW never contains epsilon, it's only terminals and the dollar sign."),
        ("S", "Why does FOLLOW of B go into FOLLOW of A and not the other way around?"),
        ("L", "Right, so think about the production B goes to alpha A. Anything that can come after B in a sentence, well, the last thing B produces is A, so that same token comes right after A. The information flows from the left hand side into the symbol at the end. It doesn't go the other way, because A can appear in lots of other places where B isn't around."),
        ("L", "So for our grammar, FOLLOW of E is close paren and dollar. Dollar because E is the start symbol, close paren because of F goes to paren E paren. E prime is at the end of E's production so it gets FOLLOW of E, same set."),
        ("L", "FOLLOW of T is plus, close paren, dollar. The plus comes from FIRST of E prime, and since E prime can vanish, T also gets FOLLOW of E. And FOLLOW of F adds star on top of that. I'll let you check that one at home."),
        ("L", "Oh, and by the way, this, computing FIRST and FOLLOW by hand for a small grammar, is a guaranteed midterm question. Every year. So practice it."),
        ("L", "Okay. Now we have everything we need, so let's actually fill in the parse table. The algorithm is two rules."),
        ("L", "For each production A goes to alpha, for every terminal a in FIRST of alpha, put A goes to alpha in the cell M of A comma a. That's the normal case, the lookahead tells you this production can start with a."),
        ("L", "And second, if epsilon is in FIRST of alpha, meaning this production can vanish, then for every terminal b in FOLLOW of A, you also put A goes to alpha in M of A comma b. That's how the epsilon productions get used."),
        ("L", "So for example E prime goes to epsilon ends up in the columns for close paren and dollar, because that's FOLLOW of E prime. And E prime goes to plus T E prime is in the plus column."),
        ("L", "Let's do a few more cells so you get the pattern. F goes to paren E paren goes in M of F comma open paren. F goes to id goes in M of F comma id. T prime goes to star F T prime is in the star column. And T prime goes to epsilon goes in FOLLOW of T prime, which is plus, close paren and dollar. Every other cell in the T prime row is empty, which means error."),
        ("L", "And that's really the whole algorithm. Two nested loops over productions and terminals. The table for this grammar has five rows and six columns and every cell has at most one entry, so this grammar is LL one."),
        ("L", "Now here's the punchline. The grammar is LL one if and only if every cell has at most one production. If you ever try to put two productions in the same cell, that's a conflict, and it means one token of lookahead is not enough to decide."),
        ("L", "Conflicts usually come from three things. Left recursion, common prefixes where you need to left factor, or the grammar is just ambiguous. And the first one is so common that we should talk about how to fix it."),
        ("L", "Common prefixes first, quickly. If you have statement goes to if expr then stmt else stmt, or if expr then stmt, both productions start with if, so both land in the if column, conflict. The fix is left factoring, pull out the common part: statement goes to if expr then stmt, then a new nonterminal for the optional else part, which is else stmt or epsilon."),
        ("L", "Yeah, um, I see some people packing up, we have like four minutes, stay with me. This is on the homework."),
        ("L", "So left recursion. A grammar is left recursive if you have something like A goes to A alpha or beta. The A calls itself as the very first thing."),
        ("L", "And for a top down parser that's a disaster, because to expand A you look at the production, it starts with A, so you expand A again, and again, you never consume any input. Infinite loop."),
        ("L", "The fix is a rewrite. A goes to A alpha or beta generates beta followed by any number of alphas, right? So we write that directly. A goes to beta A prime, and A prime goes to alpha A prime or epsilon."),
        ("L", "Same language, but now it's right recursive, so the parser always consumes beta first before it recurses. And that's exactly why our expression grammar had those E prime and T prime nonterminals, that's the left recursion already removed from E goes to E plus T."),
        ("L", "Let's do it on E goes to E plus T or T. Here alpha is plus T and beta is T. So the rewrite gives E goes to T E prime, E prime goes to plus T E prime or epsilon. And that's exactly the grammar on the slide. So now you know where it came from."),
        ("L", "One thing to watch, the rewrite changes the shape of the parse tree. Plus was left associative in the original grammar, now the tree leans right. So when you build the AST you have to fix up associativity yourself, we'll see that when we do semantic actions."),
        ("L", "There's also indirect left recursion, like A goes to B x and B goes to A y, so A reaches itself through B. For that you order the nonterminals and substitute, and then remove the direct recursion. The details are in the book, section four point three."),
        ("L", "Okay that's it for today. Next time we'll do bottom-up parsing, LR. Don't forget homework three, due Friday. See you Thursday."),
    ]
}
